# Generated by Django 4.0.5 on 2022-11-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0002_preferencia_otra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencia',
            name='detalle_preferencia',
        ),
        migrations.RemoveField(
            model_name='preferencia',
            name='otra',
        ),
    ]
