# Generated by Django 4.0.5 on 2022-12-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0029_perfiluser_foto64'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='foto64',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
